name: Gradle Clean Build
oon: [workflow_call] # yamllint disable-line rule:truthyn: [push, pull_request}
jobs:
    gradle:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v3
              with:
                  java-version: "11"
                  distribution: "adopt"

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: clean build
